name: 🧠 Universal Project Intelligence

on:
  project_v2_item:
    types: [created, edited, moved, deleted]

jobs:
  universal-processor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      projects: write
      issues: read
    
    steps:
      - name: 🌐 CAPTURE PROJECT CONTEXT
        run: |
          echo "PROJECT_TITLE=${{ github.event.project_v2_item.project.title || 'Unknown' }}" >> $GITHUB_ENV
          echo "ITEM_ID=${{ github.event.project_v2_item.id }}" >> $GITHUB_ENV
          echo "ACTION_TYPE=${{ github.event.action }}" >> $GITHUB_ENV
          
      - name: 📝 INTELLIGENT AUDIT LOGGING
        run: |
          echo "$(date -u +'%Y-%m-%dT%H:%M:%SZ') | Project: ${{ env.PROJECT_TITLE }} | Item: ${{ env.ITEM_ID }} | Action: ${{ env.ACTION_TYPE }} | By: ${{ github.actor }}" >> .audit/universal-project-log.csv
          
      - name: 💾 COMMIT AND SYNC
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .audit/universal-project-log.csv
          git commit -m "AUDIT: Project activity in ${{ env.PROJECT_TITLE }}"
          git push
